---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
  annotations:
    kubernetes.io/ingress.class: "alb"  # or nginx if you're using nginx
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: petclinic.example.com  # Replace with actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-petclinic
                port:
                  number: 80
