name: Terraform CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  TF_WORKING_DIR: terraform
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    environment: dev

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::secrets.AWS_ACCOUNT_ID:role/secrets.AWS_ROLE_NAME
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        run: tflint --recursive

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var="administrator_login_password=${{ secrets.ADMIN_PASSWORD }}" \
            -out=tfplan.out \
            -no-color > plan.txt
        continue-on-error: true

      - name: Upload plan to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ${{ env.TF_WORKING_DIR }}/plan.txt
          recreate: true
